version: '3'
services:
  dlai-finetuning-notebook:
    image: dlai-finetuning:latest
    env_file:
    - .env
    build: ./app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888" 
    volumes:
      - ./notebooks/:/app/notebooks

volumes:
      notebooks:
    
